extends: airbnb-base
rules:
  comma-dangle:
  - 0
  - array: always
    objects: always
    imports: always
    exports: always
    functions: ignore
  function-paren-newline: 0
  global-require: 0
  newline-per-chained-call: 0
  no-console: 0
  no-undef: 0
