version: 2.1
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run: gem install bundler
      - run: make setup
  test_int:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run: gem install bundler
      - run: make setup test
workflows:
  version: 2
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "35,40 21 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_int
