version: 2.1
general:
  branches:
    only:
      - master
      - clara-daily-tests
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: make setup
  test_int:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run: make setup
      - run: make test
workflows:
  version: 2
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "15,20,25 * * * *"
          filters:
            branches:
              only:
                - clara-daily-tests
    jobs:
      - test_int
